version: '3.7'
services:
  api:
    container_name: graphql-server
    build: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - DB_MONGO_CONNECTION=mongodb://root:root@mongo:27017
      - DB_MONGO_DATABASE=tasks
      - PORT=8080
      - CORS_ALLOWED_ORIGINS=*
  mongo:
    container_name: mongodb
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
